<?php
    if(!defined("MYHOST"))
        define("MYHOST","projets.iut-laval.univ-lemans.fr");
    if(!defined("MYUSER"))
        define("MYUSER","16mmi1us06");
    if(!defined("MYPASS"))
        define("MYPASS","GoUT5i97");
    if(!defined("MYDB"))
        define("MYDB","16mmi1pj06");
?>