<?php
    if(!defined("MYHOST"))
        define("MYHOST","localhost");
    if(!defined("MYUSER"))
        define("MYUSER","root");
    if(!defined("MYPASS"))
        define("MYPASS","root");
    if(!defined("MYDB"))
        define("MYDB","inventory");
?>